# Top-level playbook that initialises the application client instances for the ZDM Immersion Day training
#
# Requires an inventory file with a group called "clients" containing the public IPs of the application client instances, because we do not have a jumphost.
# These are not EIPs so they will have to be changed every time.
#
# Things that it does:
# - Install OpenJDK 11 and Maven
# - Install Docker engine
# - Install CQLSH
# - Install NoSQLBench, create activity folder, upload activity
# - Clone ZDM Demo Client
# - Clone Themis and build it

---
- name: Install Java packages and Docker engine
  hosts: clients
  become: yes

  tasks:
    - name: Install OpenJDK and Maven if not yet present
      apt:
        update_cache: yes
        name: "{{ java_packages }}"
        state: present
      vars:
        java_packages: [ 'openjdk-11-jdk', 'maven' ]

    - name: Clean up the Docker test container if it exists
      docker_container:
        name: "test"
        state: absent
    - name: Check if Docker Engine is already installed
      command: docker run --name test hello-world
      register: docker_installed
      ignore_errors: yes
    - name: Install Docker Engine if not already present
      include_tasks: tasks/install_docker.yaml
      when: docker_installed.failed
    - name: Clean up the Docker test container if it exists
      docker_container:
        name: "test"
        state: absent

- name: Install all CQL clients
  hosts: clients

  tasks:
    - name: Clean up home directory
      include_tasks: tasks/clean_up_home_dir.yaml

    - name: Install cqlsh-astra
      include_tasks: tasks/install_cqlsh.yaml

    - name: Install nb5
      include_tasks: tasks/install_nb5.yaml

    - name: Install ZDM Demo Client
      include_tasks: tasks/install_zdm_demo_client.yaml

    - name: Install Themis
      include_tasks: tasks/install_themis.yaml









