- name: Create the CDM directory
  file:
    path: /home/ubuntu/cdm
    state: directory

- name: Download the CDM jar
  get_url:
    url: https://github.com/datastax/cassandra-data-migrator/releases/download/4.1.12/cassandra-data-migrator-4.1.12.jar
    dest: /home/ubuntu/cdm/cassandra-data-migrator-4.1.12.jar

- name: Create the CDM assets directory
  file:
    path: /home/ubuntu/cdm/assets
    state: directory

- name: Download the Spark dependency jar
  get_url:
    url: https://archive.apache.org/dist/spark/spark-3.4.2/spark-3.4.2-bin-hadoop3-scala2.13.tgz
    dest: /home/ubuntu/cdm/spark-3.4.2-bin-hadoop3-scala2.13.tgz

- name: Uncompress the Spark dependency jar
  unarchive:
    src: /home/ubuntu/cdm/spark-3.4.2-bin-hadoop3-scala2.13.tgz
    dest: /home/ubuntu/cdm/
    remote_src: yes

- name: Remove archive
  file:
    path: /home/ubuntu/cdm/spark-3.4.2-bin-hadoop3-scala2.13.tgz
    state: absent

- name: Download and save locally the CDM detailed properties file
  get_url:
    url: https://raw.githubusercontent.com/datastax/cassandra-data-migrator/main/src/resources/cdm-detailed.properties
    dest: /home/ubuntu/cdm/assets/cdm.properties
